apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: k3d-fluxcd
servers: 1 # How many Kubernetes control plane nodes to run
agents: 2  # How many Kubernetes worker nodes to run
ports:
  - port: 8081:80
    nodeFilters:
      - loadbalancer