apiVersion: apps/v1
kind: Deployment
metadata:
  name: subi
spec:
  selector:
    matchLabels:
      app: subi
  template:
    metadata:
      labels:
        app: subi
    spec:
      containers:
      - name: subi
        image: pubisubi_subi:latest
        imagePullPolicy: Never
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: MassTransit__Host
            value: rabbitmq
          - name: MassTransit__Username
            value: pupu
          - name: MassTransit__Password
            value: verysecretsecret
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
